// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simonProb
double simonProb(double p, int n1, int r1, int n, int r);
RcppExport SEXP _mtdesign_simonProb(SEXP pSEXP, SEXP n1SEXP, SEXP r1SEXP, SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(simonProb(p, n1, r1, n, r));
    return rcpp_result_gen;
END_RCPP
}
// manderProb
double manderProb(double p, int n1, int r1, int r2, int n, int r);
RcppExport SEXP _mtdesign_manderProb(SEXP pSEXP, SEXP n1SEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< int >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(manderProb(p, n1, r1, r2, n, r));
    return rcpp_result_gen;
END_RCPP
}
// augmentGridC
DataFrame augmentGridC(DataFrame d);
RcppExport SEXP _mtdesign_augmentGridC(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(augmentGridC(d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mtdesign_simonProb", (DL_FUNC) &_mtdesign_simonProb, 5},
    {"_mtdesign_manderProb", (DL_FUNC) &_mtdesign_manderProb, 6},
    {"_mtdesign_augmentGridC", (DL_FUNC) &_mtdesign_augmentGridC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mtdesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
